In [ ]:
from sklearn.datasets import load_iris
import numpy as np
iris = load_iris()

Data = iris.data
Species = iris.target

print(Data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
#task1: Cross validation
#splitting data to training and testing datasets

In [ ]:
#X0 = setosa
testing_X0 = Data[:10]
training_X0 = Data[10:50]

#X1 = versicolor
testing_X1 = Data[50:60]
training_X1 = Data[60:100]

#X2 = virginica
testing_X2 = Data[100:110]
training_X2 = Data[110:150]

testing_X = np.append(testing_X0,testing_X1, axis = 0)
testing_X = np.append(testing_X,testing_X2, axis = 0)

training_X = np.append(training_X0,training_X1, axis = 0)
training_X = np.append(training_X,training_X2, axis = 0)

Species_test = []

Species_test.append(Species[:10])
Species_test.append(Species[50:60])
Species_test.append(Species[-10:])

print(training_X)
print(testing_X)


[[5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.

In [ ]:
#Functions for mean and st_dev

In [ ]:
from math import sqrt
from math import exp
from math import pi

# Calculate the mean 
def mean(values):
    return sum(values)/float(len(values))

# Calculate the standard deviation 
def st_deviation(values):
    average = mean(values)
    return sqrt(sum([(x-average)**2 for x in values]) / float(len(values)-1))


In [ ]:
#Setosa mean
mean_X0 = []
feature = []
for i in range(4):
  for j in range(40):
    feature.append((training_X0[j,i]))
  mean_X0.append(mean(feature))
  feature = []

print(mean_X0)

#Versicolor mean
mean_X1 = []
feature = []
for i in range(4):
  for j in range(40):
    feature.append((training_X1[j,i]))
  mean_X1.append(mean(feature))
  feature = []

print(mean_X1)

#Virginica mean
mean_X2 = []
feature = []
for i in range(4):
  for j in range(40):
    feature.append((training_X2[j,i]))
  mean_X2.append(mean(feature))
  feature = []

print(mean_X2)

[5.0425, 3.4574999999999996, 1.4649999999999994, 0.2525]
[5.894999999999999, 2.7449999999999997, 4.2325, 1.3124999999999998]
[6.592500000000001, 2.982499999999999, 5.497499999999999, 2.0224999999999995]


In [ ]:
#setosa_st_deviation

feature = []
st_dev_X0 = []
for i in range(4):
  for j in range(40):
    feature.append(training_X0[j,i])
  st_dev_X0.append(st_deviation(feature))
  feature = []

print(st_dev_X0)

#Versicolor_st_deviation

feature = []
st_dev_X1 = []
for i in range(4):
  for j in range(40):
    feature.append(training_X1[j,i])
  st_dev_X1.append(st_deviation(feature))
  feature = []

print(st_dev_X1)

#Virginica_st_deviation

feature = []
st_dev_X2 = []
for i in range(4):
  for j in range(40):
    feature.append(training_X2[j,i])
  st_dev_X2.append(st_deviation(feature))
  feature = []

print(st_dev_X2)

[0.3601192822328422, 0.3928120187205097, 0.18749358963400894, 0.11091114484704437]
[0.45174873887695915, 0.3063013431581926, 0.46761122357173646, 0.20404562084155442]
[0.5988825063484963, 0.32255987319391083, 0.5332471885557056, 0.27408355454458566]


In [ ]:
#Task2: Likelihood

In [ ]:
def like_fun(x, mean, st_dev):
    denominator = 2 * float(st_dev) ** 2
    number = (2 * pi ** 0.5) * denominator
    main_func = exp(-(float(x)-float(mean)) ** 2 / denominator)
    return main_func / number
Likelihood = []
feature = []
values_X0 = []
values_X1 = []
values_X2 = []
for i in range(30):
  for j in range(4):
    number = testing_X[i,j]
    values_X0.append(like_fun(number,mean_X0[j],st_dev_X0[j]))
    values_X1.append(like_fun(number,mean_X1[j],st_dev_X1[j]))
    values_X2.append(like_fun(number,mean_X2[j],st_dev_X2[j]))
  feature.append(values_X0)
  feature.append(values_X1)
  feature.append(values_X2)
  Likelihood.append(feature)
  feature = []
  values_X0 = []
  values_X1 = []
  values_X2 = []

for i in range(30):
  print(Likelihood[i])

[[1.0738319108394963, 0.9087692289284207, 3.7782802420840267, 10.250858728313261], [0.14691545315291354, 0.07206866024783808, 6.951113076841809e-09, 1.1881129556795212e-06], [0.01762099041828004, 0.37429872844998857, 7.483736639610262e-14, 4.703760066293909e-10]]
[[1.005706719279486, 0.46391684828200425, 3.7782802420840267, 10.250858728313261], [0.06111375914782357, 1.0630829190124196, 6.951113076841809e-09, 1.1881129556795212e-06], [0.007250451952312715, 1.353646400350146, 7.483736639610262e-14, 4.703760066293909e-10]]
[[0.6919164779213548, 0.7373660907280649, 2.724092825132773, 10.250858728313261], [0.020897139154542436, 0.49877956109150506, 1.8601305870865876e-09, 1.1881129556795212e-06], [0.0026684842770317127, 1.0799750092232734, 1.7404707184112627e-14, 4.703760066293909e-10]]
[[0.5112255638487764, 0.604135827496989, 3.9429868818289844, 10.250858728313261], [0.011353751167252036, 0.7680382663880885, 2.481439335480197e-08, 1.1881129556795212e-06], [0.0015525701603799674, 1.26861548

In [ ]:
#Task3: Priori

In [ ]:
f = 2
Priori_X0=len(training_X0)/len(training_X)
Priori_X1=len(training_X1)/len(training_X)
Priori_X2=len(training_X2)/len(training_X)
print("{:.{}f}".format(Priori_X0, f))
print("{:.{}f}".format(Priori_X1, f))
print("{:.{}f}".format(Priori_X2, f))

0.33
0.33
0.33


In [ ]:
#Task4: Posterior

In [ ]:
from numpy.ma.core import argmax
from numpy import prod
posterior = []
feature = []
for i in range(30):
  for j in range(3):
    post = (prod(Likelihood[i][j]) * Priori_X0)
    feature.append(post)
    post = 0
  posterior.append(feature)
  feature = []

for j in range(30):
  print(argmax(posterior[j]))


0
0
0
0
0
0
0
0
0
0
1
1
2
1
1
1
1
1
1
1
2
2
2
2
2
2
1
2
2
2


In [ ]:
#Task5: Accuracy

In [ ]:
accuracy = []
count = 0
for i in range(3):
  for j in range(10):
    accuracy.append(Species_test[i][j])
for i in range(30):
  if(argmax(posterior[i]) == accuracy[i]):
    count += 1
print(count / len(testing_X) * 100)

93.33333333333333
